name: Simple Action
on: [push]
jobs:
    hopa-script:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hopa World"
            - name: multiline script 
              run: |
                node -v 
                npm -v
            - name: Simple JS Action
              id: greet 
              uses: actions/hello-world-javascript-action@v1
              with: 
                who-to-greet: Vasiliy
            - name: ENV STUFF 
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo "${{ github.token }}"
                # git clone git@github:$GITHUB_REPOSITORY
                # git checkout $GITHUB_SHA
            - name: Checkout 
              uses: actions/checkout@v1           